# Generated by Django 5.2.8 on 2025-11-08 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_of_deal', models.CharField(choices=[('sell', 'فروش'), ('buy', 'خرید')], max_length=200)),
                ('wight', models.BigIntegerField(default=0)),
                ('soot', models.FloatField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('main_price', models.BigIntegerField(default=0)),
                ('user_debt_amount', models.BigIntegerField(default=0)),
                ('user_credit_amount', models.BigIntegerField(default=0)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('unpaid', 'پرداخت نشده'), ('payed', 'پرداخت شده')], max_length=100, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('not_deliver', 'تحویل داده نشده'), ('deliver', 'تحویل داده شده')], max_length=100, null=True)),
                ('deal_status', models.CharField(blank=True, choices=[('unknown', 'نامشخص'), ('expire', 'فسخ شده'), ('confirm', 'تایید شده')], max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('factor_number', models.IntegerField(default=0)),
                ('ok_responde', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('type_of_payment', models.CharField(choices=[('card', 'کارت به کارت'), ('online', 'آنلاین'), ('cash', 'نقدی')], max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('account_destination_number', models.BigIntegerField(default=0)),
                ('account_genesis_number', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('confirm', 'تایید شده'), ('failed', 'ناموفق')], default='failed', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
