# Generated by Django 5.2.8 on 2025-11-10 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Module', '0001_initial'),
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Product_Data_Module.product'),
            preserve_default=False,
        ),
    ]
