# Generated by Django 5.2.8 on 2025-11-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Module', '0002_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='wight',
            new_name='weight',
        ),
    ]
