# Generated by Django 5.2.8 on 2025-11-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Module', '0003_rename_wight_order_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_order',
            field=models.CharField(choices=[('admin_pannel', 'پنل ادمین'), ('user_pannel', 'پنل کاربری')], default=10, max_length=200),
            preserve_default=False,
        ),
    ]
