# Generated by Django 5.2.8 on 2025-11-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account_Module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fee_percent', models.BigIntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('by_weight', 'بر اساس وزن'), ('by_quantity', 'بر اساس تعداد')], default='by_quantity', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product_Data_Module.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Module.user')),
            ],
        ),
    ]
