# Generated by Django 5.2.8 on 2025-11-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Data_Module', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='NewProduct/images/'),
        ),
    ]
