# Generated by Django 5.2.8 on 2025-11-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Data_Module', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_creator',
        ),
    ]
