# Generated by Django 5.2.8 on 2025-11-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0001_initial'),
        ('Product_Data_Module', '0004_rename_user_product_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account_Module.user'),
        ),
    ]
