# Generated by Django 5.2.8 on 2025-11-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Data_Module', '0005_alter_product_user_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_sell', models.BigIntegerField(default=0)),
                ('base_price_buy', models.BigIntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('is_exist', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product_Data_Module.product')),
            ],
        ),
    ]
