# Generated by Django 5.2.8 on 2025-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_weight_sellbuy_order',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_wheight_automate_order',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_weight_sellbuy_order',
            field=models.BigIntegerField(default=0),
        ),
    ]
