# Generated by Django 5.2.8 on 2025-11-08 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorCreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_kode', models.IntegerField()),
                ('factor_number', models.PositiveBigIntegerField()),
                ('row_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('document_type', models.CharField(choices=[('creditor', 'طلب ما'), ('debt', 'بدهی ما')], max_length=200)),
                ('price', models.BigIntegerField()),
                ('for_about', models.CharField(max_length=300)),
                ('weight', models.BigIntegerField()),
                ('description', models.TextField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GetMoneyFromBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_kode', models.IntegerField()),
                ('factor_number', models.PositiveBigIntegerField()),
                ('row_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('get_or_pay_money', models.CharField(choices=[('get_money', 'دریافت از مشتری'), ('pay_money', 'پرداخت به مشتری')], max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('price', models.BigIntegerField()),
                ('cod_rahgiry', models.BigIntegerField()),
                ('description', models.TextField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportMelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('SabtKolORMovaghat', models.CharField(choices=[('permanent', 'ثبت کل'), ('temporary', 'موقت')], max_length=200)),
                ('customer_kode', models.IntegerField()),
                ('factor_number', models.PositiveBigIntegerField()),
                ('row_number', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ayar', models.IntegerField()),
                ('ang_number', models.IntegerField()),
                ('lab_name', models.CharField(max_length=200)),
                ('export_or_import', models.CharField(choices=[('import', 'ورود '), ('export', 'خروج')], max_length=200)),
                ('melt_ot_etc', models.CharField(choices=[('melt', 'آبشده '), ('ect', 'متفرقه ')], max_length=200)),
                ('description', models.TextField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportExportMeltAllChash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('customer_kode', models.IntegerField()),
                ('factor_number', models.PositiveBigIntegerField()),
                ('row_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('import_or_export', models.CharField(choices=[('import', 'ورود '), ('export', 'خروج')], max_length=200)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
