# Generated by Django 5.2.8 on 2025-11-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account_Module', '0002_user_image_profile'),
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_sell', models.BigIntegerField(default=0)),
                ('profit_buy', models.BigIntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('active_for_sell', models.BooleanField(default=True)),
                ('active_for_buy', models.BooleanField(default=True)),
                ('max_weight_buy', models.BooleanField(default=0)),
                ('min_weight_buy', models.BooleanField(default=0)),
                ('max_weight_sell', models.BooleanField(default=0)),
                ('min_weight_sell', models.BooleanField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product_Data_Module.productprice')),
            ],
        ),
        migrations.CreateModel(
            name='Access_By_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_sell', models.BigIntegerField(default=0)),
                ('profit_buy', models.BigIntegerField(default=0)),
                ('time', models.TimeField(auto_now=True)),
                ('active_for_sell', models.BooleanField(default=True)),
                ('active_for_buy', models.BooleanField(default=True)),
                ('max_weight_buy', models.BigIntegerField(default=0)),
                ('min_weight_buy', models.BigIntegerField(default=0)),
                ('max_weight_sell', models.BigIntegerField(default=0)),
                ('min_weight_sell', models.BigIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Data_Module.productprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account_Module.user')),
            ],
        ),
        migrations.CreateModel(
            name='Access_By_UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_sell', models.BigIntegerField(default=0)),
                ('profit_buy', models.BigIntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('active_for_sell', models.BooleanField(default=True)),
                ('active_for_buy', models.BooleanField(default=True)),
                ('max_weight_buy', models.BigIntegerField(default=0)),
                ('min_weight_buy', models.BigIntegerField(default=0)),
                ('max_weight_sell', models.BigIntegerField(default=0)),
                ('min_weight_sell', models.BigIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_settings', to='Account_Module.usergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access_settings', to='Product_Data_Module.productprice')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'product'], name='Price_Mnage_group_i_bc46e6_idx')],
                'unique_together': {('group', 'product')},
            },
        ),
    ]
