# Generated by Django 5.2.8 on 2025-11-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0001_initial'),
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_all',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Data_Module.productprice'),
        ),
    ]
