# Generated by Django 5.2.8 on 2025-11-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0003_alter_access_all_product'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='access_by_usergroup',
            name='Price_Mnage_group_i_bc46e6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='access_by_usergroup',
            unique_together=set(),
        ),
    ]
