# Generated by Django 5.2.8 on 2025-11-08 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0004_remove_access_by_usergroup_price_mnage_group_i_bc46e6_idx_and_more'),
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_by_user',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Data_Module.product'),
        ),
        migrations.AlterField(
            model_name='access_by_usergroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access_settings', to='Product_Data_Module.product'),
        ),
    ]
