# Generated by Django 5.2.8 on 2025-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0005_alter_access_by_user_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_all',
            name='max_weight_buy',
        ),
        migrations.RemoveField(
            model_name='access_all',
            name='max_weight_sell',
        ),
        migrations.RemoveField(
            model_name='access_all',
            name='min_weight_buy',
        ),
        migrations.RemoveField(
            model_name='access_all',
            name='min_weight_sell',
        ),
    ]
