# Generated by Django 5.2.8 on 2025-11-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0006_remove_access_all_max_weight_buy_and_more'),
        ('Product_Data_Module', '0006_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_all',
            name='automate_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access_all',
            name='automate_price',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Config_Price_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Data_Module.product')),
            ],
        ),
    ]
