# Generated by Django 5.2.8 on 2025-11-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0007_access_all_automate_order_access_all_automate_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config_Price_Manage',
        ),
    ]
