# Generated by Django 5.2.8 on 2025-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price_Mnage_Module', '0008_delete_config_price_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Price_Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_access_all', models.BooleanField(default=False)),
                ('shop_status', models.BooleanField(default=True)),
            ],
        ),
    ]
