# Generated by Django 5.2.8 on 2025-11-06 11:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('active_session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('request_status', models.CharField(choices=[('در انتظار بررسی', 'در انتظار بررسی'), ('معرفی معرف', 'معرفی معرف'), ('واگذاری وثیقه', 'واگذاری وثیقه'), ('تأیید شده', 'تأیید شده')], default='در انتظار بررسی', max_length=100)),
                ('guarantee_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('1', 'بنکداران (بازار)'), ('2', 'همکار'), ('3', 'متفرقه'), ('4', 'سازنده'), ('5', 'مخارج'), ('6', 'کیفی'), ('7', 'تراشکار'), ('8', 'ویترین'), ('9', 'جواهر'), ('10', 'صندوق'), ('11', 'سرمایه'), ('12', 'کارمندان')], max_length=100, null=True)),
                ('cod_meli', models.PositiveBigIntegerField(blank=True, null=True)),
                ('invite_code', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('user_status', models.CharField(choices=[('user', 'کاربر معمولی '), ('employee', 'کارمند '), ('admin', 'ادمین')], default='user', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('shomare_shaba', models.PositiveBigIntegerField(blank=True, null=True)),
                ('shomare_hesab', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tah_hesab_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('can_invite', models.BooleanField(default=False)),
                ('rasteh', models.PositiveBigIntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('max_gold_debt_amount', models.BigIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account_Module.user')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='Account_Module.usergroup')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
