# Generated by Django 5.2.8 on 2025-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
