# Generated by Django 5.2.8 on 2025-11-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0002_user_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sell_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
