# Generated by Django 5.2.8 on 2025-11-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0003_user_gold_limit_user_price_limit_user_sell_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gold_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='price_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sell_limit',
        ),
    ]
