# Generated by Django 5.2.8 on 2025-11-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0004_remove_user_gold_limit_remove_user_price_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
