# Generated by Django 5.2.8 on 2025-11-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='possibel_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
